services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $rootDir: '%kernel.project_dir%'
      $env: '%kernel.environment%'
      $bundleConfig: '%huh_twig_support%'

  HeimrichHannot\TwigSupportBundle\EventListener\RenderListener:
    public: true

  HeimrichHannot\TwigSupportBundle\Cache\TemplateCache: ~
  HeimrichHannot\TwigSupportBundle\Filesystem\TwigTemplateLocator: ~
  HeimrichHannot\TwigSupportBundle\Helper\NormalizerHelper: ~