services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $rootDir: '%kernel.project_dir%'
      $env: '%kernel.environment%'


  HeimrichHannot\TwigSupportBundle\EventListener\RenderListener:
    public: true

  HeimrichHannot\TwigSupportBundle\Filesystem\TwigTemplateLocator: ~

  HeimrichHannot\TwigSupportBundle\Cache\TemplateCache: ~